name: 'shootemdown'
version: 0.0.1
description: A classic left right shooter with elements of Space Invaders, Galaxians and Centipede.
author: Davy Mitchell <daftspaniel@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  simplegamelib: '^0.0.13'
transformers:
- dart_to_js_script_rewriter